name: '[QE] Lint'

on:
  push:
    branches:
      - master
      - main
      - release/*
      - feature/*
      - fix/*
      - chore/*
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache for node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install base packages
        run: yarn install --frozen-lockfile
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

      - name: Install react packages
        run: yarn install --frozen-lockfile
        working-directory: ./react
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

      - name: Lint
        run: yarn lint
